name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

env:
  HUGGINGFACEHUB_API_TOKEN: "${{secrets.HUGGINGFACE_KEY_ID}}"

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete old docker images
      run: sudo docker rmi -f $(docker image ls -a -q)
    - name: Pull docker image from docker hub
      run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/cover_letter_gen:latest
    - name: Delete the old docker container
      run: sudo docker rm -f cover_letter_gen_container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8501:8501 --name cover_letter_gen_container ${{secrets.DOCKER_USERNAME}}/cover_letter_gen:latest
