name: CI pipeline

on:
  push:
    branches: [ "main" ]

env:
  HUGGINGFACEHUB_API_TOKEN: "${{secrets.HUGGINGFACE_KEY_ID}}"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t cover_letter_gen .
    - name: Tag docker image
      run: docker tag cover_letter_gen ${{secrets.DOCKER_USERNAME}}/cover_letter_gen:latest
    - name: Push to Dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/cover_letter_gen:latest
